title: "Charlotte Durand"
description: "Personal website"
baseurl: "" # change if serving from subpath
url: "https://durandcharlotte.durandcharlotte.github.io" # update to your site URL

author:
  name: "Charlotte Durand"
  role: "PostDoc @IGE"
  email: "charlotte.durand1@univ-grenoble-alpes.fr"
  website: "https://durandcharlotte.durandcharlotte.github.io"
  bio: ""

markdown: kramdown
theme: null
plugins:
  - jekyll-gist
  - jekyll-github-metadata

permalink: /:title/